/**
 * Emerald High bell schedules by day (reference times from school documents).
 * Fallon Middle keeps a single reference block schedule.
 */
window.EMERALD_SCHEDULE_BY_DAY = {
  Monday: {
    title: "Monday — all periods",
    note: "Period 0 and Period 7 are optional periods with limited class offerings.",
    rows: [
      { period: "Period 0 (optional)", start: "7:15 AM", end: "8:20 AM", length: "65 min" },
      { period: "Period 1", start: "8:30 AM", end: "9:22 AM", length: "52 min" },
      { period: "Period 2", start: "9:28 AM", end: "10:20 AM", length: "52 min" },
      { period: "Period 3", start: "10:26 AM", end: "11:18 AM", length: "52 min" },
      { period: "Period 4", start: "11:24 AM", end: "12:16 PM", length: "52 min" },
      { period: "LUNCH", start: "12:16 PM", end: "12:51 PM", length: "35 min" },
      { period: "ACCESS Period", start: "12:57 PM", end: "1:29 PM", length: "32 min" },
      { period: "Period 5", start: "1:35 PM", end: "2:27 PM", length: "52 min" },
      { period: "Period 6", start: "2:33 PM", end: "3:25 PM", length: "52 min" },
      { period: "Period 7 (optional)", start: "3:31 PM", end: "4:36 PM", length: "65 min" },
    ],
  },
  Tuesday: {
    title: "Tuesday — all periods",
    note: "Period 0 and Period 7 are optional with limited offerings.",
    rows: [
      { period: "Period 0", start: "7:15 AM", end: "8:20 AM", length: "65 min" },
      { period: "Period 1", start: "8:30 AM", end: "9:28 AM", length: "58 min" },
      { period: "Period 2", start: "9:34 AM", end: "10:32 AM", length: "58 min" },
      { period: "Period 3", start: "10:38 AM", end: "11:38 AM", length: "60 min" },
      { period: "Period 4", start: "11:44 AM", end: "12:42 PM", length: "58 min" },
      { period: "LUNCH", start: "12:42 PM", end: "1:17 PM", length: "35 min" },
      { period: "Period 5", start: "1:23 PM", end: "2:21 PM", length: "58 min" },
      { period: "Period 6", start: "2:27 PM", end: "3:25 PM", length: "58 min" },
      { period: "Period 7", start: "3:31 PM", end: "4:36 PM", length: "65 min" },
    ],
  },
  Wednesday: {
    title: "Wednesday — odd periods (block)",
    note: "Staff collaboration occurs before student periods; student day begins Period 1.",
    rows: [
      { period: "Staff collaboration (staff only)", start: "8:00 AM", end: "8:55 AM", length: "55 min" },
      { period: "Period 1", start: "9:00 AM", end: "10:30 AM", length: "90 min" },
      { period: "Period 3", start: "10:36 AM", end: "12:06 PM", length: "90 min" },
      { period: "LUNCH", start: "12:06 PM", end: "12:41 PM", length: "35 min" },
      { period: "ACCESS Period", start: "12:47 PM", end: "1:49 PM", length: "62 min" },
      { period: "Period 5", start: "1:55 PM", end: "3:25 PM", length: "90 min" },
    ],
  },
  Thursday: {
    title: "Thursday — even periods (block)",
    note: "Period 0 and Period 7 are optional with limited offerings.",
    rows: [
      { period: "Period 0 (optional)", start: "7:15 AM", end: "8:20 AM", length: "65 min" },
      { period: "Period 2", start: "8:30 AM", end: "10:00 AM", length: "90 min" },
      { period: "Period 4", start: "10:06 AM", end: "11:36 AM", length: "90 min" },
      { period: "LUNCH", start: "11:36 AM", end: "12:11 PM", length: "35 min" },
      { period: "ACCESS Period", start: "12:17 PM", end: "1:09 PM", length: "52 min" },
      { period: "Period 6", start: "1:15 PM", end: "2:45 PM", length: "90 min" },
      { period: "Period 7 (optional)", start: "2:51 PM", end: "3:56 PM", length: "65 min" },
    ],
  },
  Friday: {
    title: "Friday — all periods",
    note: "Same structure as Tuesday. Period 0 and Period 7 optional.",
    rows: [
      { period: "Period 0 (optional)", start: "7:15 AM", end: "8:20 AM", length: "65 min" },
      { period: "Period 1", start: "8:30 AM", end: "9:28 AM", length: "58 min" },
      { period: "Period 2", start: "9:34 AM", end: "10:32 AM", length: "58 min" },
      { period: "Period 3", start: "10:38 AM", end: "11:38 AM", length: "60 min" },
      { period: "Period 4", start: "11:44 AM", end: "12:42 PM", length: "58 min" },
      { period: "LUNCH", start: "12:42 PM", end: "1:17 PM", length: "35 min" },
      { period: "Period 5", start: "1:23 PM", end: "2:21 PM", length: "58 min" },
      { period: "Period 6", start: "2:27 PM", end: "3:25 PM", length: "58 min" },
      { period: "Period 7 (optional)", start: "3:31 PM", end: "4:36 PM", length: "65 min" },
    ],
  },
};

window.SCHOOL_SCHEDULES = {
  "Emerald High School": { type: "emerald_by_day" },
  "Fallon Middle School": {
    type: "flat",
    label: "Fallon Middle — 2025-2026 bell reference",
    periods: [
      { id: "Zero Period", time: "7:40 – 8:30" },
      { id: "Period 1", time: "8:35 – 9:27" },
      { id: "Period 2", time: "9:31 – 10:21" },
      { id: "Nutrition Break", time: "10:21 – 10:29" },
      { id: "Period 3", time: "10:29 – 11:19" },
      { id: "Lunch / Period 4", time: "11:19 – 12:48" },
      { id: "Period 5", time: "12:52 – 1:42" },
      { id: "Advisory / Academic Prep", time: "1:46 – 2:11" },
      { id: "Period 6", time: "2:15 – 3:05" },
    ],
  },
};

(function () {
  const staff = ["Emerald Faculty"];

  function ap(title, teachers) {
    return { level: "AP", title, teachers: teachers || staff };
  }
  function hn(title, teachers) {
    return { level: "Honors", title, teachers: teachers || staff };
  }
  function cp(title, teachers) {
    return { level: "CP", title, teachers: teachers || staff };
  }
  function el(title, teachers) {
    return { level: "Elective", title, teachers: teachers || staff };
  }
  function acc(title, teachers) {
    return { level: "Accelerated", title, teachers: teachers || staff };
  }

  window.COURSE_CATALOG = {
    English: [
      ap("AP English Language and Composition"),
      ap("AP English Literature and Composition"),
      hn("Honors English 9"),
      hn("Honors English 10"),
      hn("Honors English 11"),
      hn("Honors English 12"),
      hn("Honors World Literature"),
      hn("Honors American Literature"),
      cp("English 9"),
      cp("English 10"),
      cp("English 11"),
      cp("English 12"),
      cp("Expository Reading and Writing (ERWC)"),
      cp("English Language Development 1"),
      cp("English Language Development 2"),
      cp("English Language Development 3"),
      el("Creative Writing"),
      el("Journalism"),
      el("Speech and Debate"),
      el("Film as Literature"),
    ],
    Mathematics: [
      ap("AP Calculus AB"),
      ap("AP Calculus BC"),
      ap("AP Precalculus"),
      ap("AP Statistics"),
      hn("Honors Algebra 1"),
      hn("Honors Geometry"),
      hn("Honors Algebra 2"),
      hn("Honors Precalculus"),
      hn("Honors Trigonometry / Math Analysis"),
      hn("Honors Statistics"),
      acc("Accelerated Math 7"),
      acc("Accelerated Math 8"),
      cp("Algebra 1"),
      cp("Geometry"),
      cp("Algebra 2"),
      cp("Precalculus"),
      cp("Statistics"),
      cp("Financial Algebra"),
      cp("Consumer Math"),
      el("Data Science"),
      el("Discrete Mathematics Topics"),
    ],
    Science: [
      ap("AP Biology"),
      ap("AP Chemistry"),
      ap("AP Physics 1"),
      ap("AP Physics 2: Algebra-Based"),
      ap("AP Physics C: Mechanics"),
      ap("AP Physics C: Electricity and Magnetism"),
      ap("AP Environmental Science"),
      hn("Honors Biology"),
      hn("Honors Chemistry"),
      hn("Honors Physics"),
      hn("Honors Anatomy and Physiology"),
      hn("Honors Integrated Science"),
      cp("Biology"),
      cp("Chemistry"),
      cp("Physics"),
      cp("Integrated Science 1"),
      cp("Integrated Science 2"),
      cp("Earth and Space Science"),
      el("Marine Biology"),
      el("Astronomy"),
      el("Forensic Science"),
    ],
    "Social Studies": [
      ap("AP United States History"),
      ap("AP World History: Modern"),
      ap("AP European History"),
      ap("AP Human Geography"),
      ap("AP United States Government and Politics"),
      ap("AP Comparative Government and Politics"),
      ap("AP Macroeconomics"),
      ap("AP Microeconomics"),
      ap("AP Psychology"),
      hn("Honors World History"),
      hn("Honors United States History"),
      hn("Honors American Government"),
      hn("Honors Economics"),
      hn("Honors Sociology"),
      cp("World History"),
      cp("United States History"),
      cp("American Government"),
      cp("Economics"),
      cp("Geography"),
      cp("Modern World Studies"),
      el("Ethnic Studies"),
      el("Law and Society"),
    ],
    "World Language": [
      ap("AP Spanish Language and Culture"),
      ap("AP Spanish Literature and Culture"),
      ap("AP French Language and Culture"),
      ap("AP German Language and Culture"),
      ap("AP Italian Language and Culture"),
      ap("AP Latin"),
      ap("AP Chinese Language and Culture"),
      ap("AP Japanese Language and Culture"),
      ap("AP Korean Language and Culture"),
      ap("AP Portuguese Language and Culture"),
      hn("Honors Spanish 2"),
      hn("Honors Spanish 3"),
      hn("Honors Spanish 4"),
      hn("Honors French 3"),
      hn("Honors French 4"),
      hn("Honors German 3"),
      cp("Spanish 1"),
      cp("Spanish 2"),
      cp("Spanish 3"),
      cp("Spanish 4"),
      cp("Spanish for Native Speakers"),
      cp("French 1"),
      cp("French 2"),
      cp("French 3"),
      cp("German 1"),
      cp("German 2"),
      cp("Mandarin 1"),
      cp("Mandarin 2"),
      el("American Sign Language 1"),
      el("American Sign Language 2"),
    ],
    "Visual & Performing Arts": [
      ap("AP Art History"),
      ap("AP Art and Design: 2-D Art and Design"),
      ap("AP Art and Design: 3-D Art and Design"),
      ap("AP Art and Design: Drawing"),
      ap("AP Music Theory"),
      hn("Honors Wind Ensemble"),
      hn("Honors Orchestra"),
      hn("Honors Chamber Choir"),
      hn("Honors Art Studio"),
      hn("Honors Theater Production"),
      cp("Art 1"),
      cp("Art 2"),
      cp("Ceramics"),
      cp("Photography"),
      cp("Digital Photography"),
      cp("Concert Band"),
      cp("Symphonic Band"),
      cp("Orchestra"),
      cp("Choir"),
      cp("Theater Arts"),
      cp("Dance 1"),
      el("Digital Media Arts"),
      el("Guitar"),
      el("Piano Lab"),
    ],
    "Physical Education & Health": [
      hn("Honors Athletic Training / Sports Medicine Intro"),
      cp("Physical Education 9"),
      cp("Physical Education 10"),
      cp("Physical Education 11"),
      cp("Physical Education 12"),
      cp("Strength and Conditioning"),
      cp("Team Sports"),
      cp("Lifetime Fitness"),
      cp("Health"),
      el("Yoga and Mindfulness"),
      el("Outdoor Education"),
    ],
    "Career & Technical Education (CTE)": [
      ap("AP Computer Science A"),
      ap("AP Computer Science Principles"),
      hn("Honors Engineering Design"),
      hn("Honors Robotics"),
      hn("Honors Business Management"),
      cp("Introduction to Business"),
      cp("Marketing"),
      cp("Accounting 1"),
      cp("Intro to Programming"),
      cp("Web Design"),
      cp("Graphic Design for Production"),
      cp("Automotive Technology 1"),
      cp("Woodworking / Construction"),
      cp("Child Development"),
      cp("Culinary Arts 1"),
      el("Entrepreneurship Lab"),
      el("Drone Technology"),
      el("Cybersecurity"),
      el("Digital Electronics"),
      el("Sports and Entertainment Marketing"),
    ],
    "Middle School Core & Electives": [
      cp("English Language Arts 6"),
      cp("English Language Arts 7"),
      cp("English Language Arts 8"),
      acc("Accelerated English 7"),
      acc("Accelerated English 8"),
      cp("Math 6"),
      cp("Math 7"),
      cp("Math 8"),
      acc("Accelerated Math 7"),
      acc("Accelerated Math 8"),
      cp("Life Science 7"),
      cp("Physical Science 8"),
      cp("World History 6"),
      cp("World History 7"),
      cp("United States History 8"),
      cp("Physical Education 6"),
      cp("Physical Education 7"),
      cp("Physical Education 8"),
      el("Art Exploration"),
      el("Band"),
      el("Choir"),
      el("Drama"),
      el("Gateway To Technology"),
      el("Leadership"),
      el("Spanish 1A"),
      el("Spanish 1B"),
    ],
    "Capstone & Research": [
      ap("AP Seminar"),
      ap("AP Research"),
      ap("AP African American Studies"),
      hn("Honors Research Methods"),
      hn("Honors Service Leadership Capstone"),
      cp("Senior Capstone Project"),
      cp("College and Career Capstone Seminar"),
      cp("STEM Capstone Lab"),
      el("Independent Study (approved)"),
    ],
    Electives: [
      hn("Honors Peer Tutoring Leadership"),
      cp("Study Skills / Academic Support"),
      cp("AVID"),
      cp("Leadership"),
      cp("Yearbook"),
      cp("Student Government"),
      el("Library Media Assistant"),
      el("Community Internship"),
    ],
  };

  const hs = (level, title, grades) => ({
    level: /^AP\b/.test(title) || /\bAP\b/.test(title) ? "AP" : level,
    title,
    grades: grades.map(String),
    schoolTypes: ["high"],
    teachers: staff,
  });
  const ms = (level, title, grades) => ({ level, title, grades: grades.map(String), schoolTypes: ["middle"], teachers: ["Fallon Faculty"] });

  window.COURSE_CATALOG = {
    English: [
      hs("CP", "English 1", [9]),
      hs("CP", "English 1 Advanced", [9]),
      hs("CP", "English 2", [10]),
      hs("CP", "English 2 Advanced", [10]),
      hs("CP", "English 3", [11]),
      hs("AP", "AP English Language", [11, 12]),
      hs("CP", "Expository Writing", [12]),
      hs("CP", "Deconstructing Race & Gender", [12]),
      hs("AP", "AP English Literature", [12]),
      hs("CP", "African American Literature", [12]),
      hs("CP", "Asian American Experience", [12]),
      hs("CP", "Contemporary Issues through Classic Scientific Literature", [12]),
      hs("CP", "Creative Writing", [12]),
      hs("CP", "Exploring Society through Dystopian Literature", [12]),
      hs("CP", "Film as Literature", [12]),
      hs("CP", "Podcasting and Storytelling", [12]),
      hs("CP", "Gothic Literature: The Hallmark of Horror", [12]),
      hs("CP", "ELD 1", [9, 10, 11, 12]),
      hs("CP", "ELD 2", [9, 10, 11, 12]),
      hs("CP", "ELD 3", [9, 10, 11, 12]),
      hs("CP", "ELD 4", [11, 12]),
      ms("CP", "English Language Arts 6", [6]),
      ms("CP", "English Language Arts 7", [7]),
      ms("CP", "English Language Arts 8", [8]),
    ],
    Mathematics: [
      hs("CP", "Algebra 1", [9, 10, 11]),
      hs("CP", "Geometry", [9, 10, 11, 12]),
      hs("CP", "Algebra II", [9, 10, 11, 12]),
      hs("CP", "Advanced Algebra 2", [9, 10, 11, 12]),
      hs("CP", "Precalculus", [9, 10, 11, 12]),
      hs("AP", "AP Precalculus", [9, 10, 11, 12]),
      hs("CP", "Calculus", [10, 11, 12]),
      hs("CP", "Statistics", [10, 11, 12]),
      hs("AP", "AP Statistics", [10, 11, 12]),
      hs("AP", "AP Calculus AB", [10, 11, 12]),
      hs("AP", "AP Calculus BC", [11, 12]),
      ms("CP", "Math 6", [6]),
      ms("CP", "Math 7", [7]),
      ms("CP", "Math 8", [8]),
      ms("Accelerated", "Accelerated Math 7", [7]),
      ms("Accelerated", "Accelerated Math 8", [8]),
    ],
    Science: [
      hs("CP", "Biology", [9, 10, 11, 12]),
      hs("CP", "Chemistry", [10, 11, 12]),
      hs("Honors", "Honors Chemistry", [10, 11, 12]),
      hs("AP", "AP Chemistry", [10, 11, 12]),
      hs("CP", "Physics in the Universe", [10, 11, 12]),
      hs("Honors", "Honors Physics", [11, 12]),
      hs("CP", "Anatomy and Physiology", [11, 12]),
      hs("CP", "Earth and Space Science", [10, 11, 12]),
      hs("CP", "Forensics Science", [11, 12]),
      hs("CP", "Marine Science", [11, 12]),
      hs("CP", "Zoology", [11, 12]),
      hs("AP", "AP Biology", [11, 12]),
      hs("AP", "AP Physics C Mechanics", [11, 12]),
      hs("AP", "AP Environmental Science", [11, 12]),
      ms("CP", "Life Science 7", [7]),
      ms("CP", "Physical Science 8", [8]),
    ],
    "Social Studies": [
      hs("Honors", "AP Human Geography", [9, 10, 11]),
      hs("CP", "World History", [10]),
      hs("AP", "AP World History", [10]),
      hs("CP", "U.S. History", [11]),
      hs("AP", "AP U.S. History", [11]),
      hs("Honors", "AP African American Studies", [10, 11, 12]),
      hs("AP", "AP Psychology", [11]),
      hs("CP", "Ethnic Studies 1", [10, 11]),
      hs("CP", "Media Literacy: How to Trust What You Read and Hear", [10, 11]),
      hs("CP", "Personal Finance: Managing Your Money to Meet Your Goals", [10, 11]),
      hs("CP", "World War II", [10, 11]),
      hs("CP", "Civics", [12]),
      hs("Honors", "Honors US Government and Politics", [12]),
      hs("AP", "AP Government & Politics", [12]),
      hs("CP", "Economics", [12]),
      hs("AP", "AP Microeconomics", [12]),
      hs("AP", "AP Macroeconomics", [12]),
      ms("CP", "World History 6", [6]),
      ms("CP", "World History 7", [7]),
      ms("CP", "United States History 8", [8]),
    ],
    "World Language": [
      hs("CP", "Chinese/Mandarin 1", [9, 10, 11]),
      hs("CP", "Chinese/Mandarin 2", [9, 10, 11]),
      hs("CP", "Chinese/Mandarin 3", [9, 10, 11]),
      hs("Honors", "Honors Chinese Mandarin 4", [10, 11]),
      hs("AP", "AP Chinese Language and Culture", [10, 11]),
      hs("CP", "French 1", [9, 10, 11]),
      hs("CP", "French 2", [9, 10, 11]),
      hs("CP", "French 3", [9, 10, 11]),
      hs("Honors", "Honors French 4", [10, 11]),
      hs("AP", "AP French", [11]),
      hs("CP", "Korean 1", [9, 10, 11]),
      hs("CP", "Korean 2", [9, 10, 11]),
      hs("CP", "Korean 3", [9, 10, 11]),
      hs("CP", "Spanish 1", [9, 10, 11]),
      hs("CP", "Spanish 2", [9, 10, 11]),
      hs("CP", "Spanish 3", [9, 10, 11]),
      hs("Honors", "Honors Spanish 4", [10, 11]),
      hs("AP", "AP Spanish Language", [10, 11]),
      ms("CP", "Spanish 1A", [7, 8]),
      ms("CP", "Spanish 1B", [8]),
    ],
    Arts: [
      hs("CP", "Design 1", [9, 10, 11]),
      hs("CP", "Drawing 1", [9, 10, 11]),
      hs("CP", "Graphic Publications (Yearbook)", [9, 10, 11]),
      hs("Honors", "Honors Yearbook", [10, 11]),
      hs("CP", "Sculpture and Ceramics", [9, 10, 11]),
      hs("CP", "Video Production 1", [9, 10, 11]),
      hs("CP", "Video Production 2", [9, 10, 11]),
      hs("Honors", "Honors Video Production 3", [11]),
      hs("Honors", "Honors Ceramics", [10, 11]),
      hs("AP", "AP 2-D Art and Design", [10, 11]),
      hs("AP", "AP 3-D Art and Design", [10, 11]),
      hs("AP", "AP Drawing", [10, 11]),
      hs("CP", "Dance 1", [9, 10, 11]),
      hs("CP", "Dance 2", [9, 10, 11]),
      hs("CP", "Drama 1", [9, 10, 11]),
      hs("CP", "Drama 2", [9, 10, 11]),
      hs("CP", "Intro to Musical Theater", [9, 10, 11]),
      hs("CP", "Concert Choir", [9, 10, 11]),
      hs("CP", "Show Choir", [9, 10, 11]),
      hs("CP", "Band 1 - Concert Band", [9, 10, 11]),
      hs("CP", "Band 2 - Symphonic Band", [9, 10, 11]),
      hs("Honors", "Honors Band 3 - Jazz Ensemble", [9, 10, 11]),
      hs("Honors", "Honors Band 3 - Wind Ensemble", [9, 10, 11]),
      hs("CP", "Guitar 1", [10, 11]),
      hs("CP", "Guitar 2", [10, 11]),
      hs("CP", "Orchestra 1 - String Orchestra", [9, 10, 11]),
      hs("CP", "Orchestra 2 - Philharmonic Orchestra", [9, 10, 11]),
      hs("Honors", "Orchestra 3 - Honors Chamber Orchestra", [9, 10, 11]),
      ms("Elective", "Art Exploration", [6, 7, 8]),
      ms("Elective", "Band", [6, 7, 8]),
      ms("Elective", "Choir", [6, 7, 8]),
      ms("Elective", "Drama", [6, 7, 8]),
    ],
    "Career & Technical Education": [
      hs("CP", "Culinary Arts", [9, 10, 11]),
      hs("CP", "PLTW Intro to Engineering Design", [9, 10, 11]),
      hs("Honors", "PLTW Honors Principles of Engineering", [10]),
      hs("CP", "PLTW Computer Science Essentials", [9, 10, 11]),
      hs("Honors", "PLTW AP Computer Science Principles", [10]),
      hs("Honors", "PLTW Honors Capstone", [11]),
      hs("Honors", "AP Computer Science Principles", [11]),
      hs("Honors", "AP Computer Science Applications", [11]),
      hs("CP", "AVID 9", [9]),
      hs("CP", "AVID 10", [10]),
      hs("CP", "AVID 11", [11]),
      hs("CP", "Student Leadership", [10, 11]),
      hs("CP", "Student Assistant", [11]),
      hs("AP", "AP Seminar", [11]),
      hs("AP", "AP Research", [11]),
      hs("CP", "Human Body Systems", [10]),
      hs("Honors", "Medical Interventions Honors", [11]),
      ms("Elective", "Gateway To Technology", [6, 7, 8]),
      ms("Elective", "Leadership", [7, 8]),
    ],
    "Physical Education & Health": [
      hs("CP", "Contemporary Health", [9]),
      hs("CP", "Freshman PE", [9]),
      hs("CP", "Archery Level 1", [10, 11]),
      hs("CP", "Dance 1 (PE)", [10, 11]),
      hs("CP", "Dance 2 (PE)", [10, 11]),
      hs("CP", "Team Sports", [10, 11]),
      hs("CP", "Team Sports (0 Period)", [10, 11]),
      hs("CP", "Intro to Weight Lifting", [10, 11]),
      hs("CP", "Intro to Weight Lifting (0 Period)", [10, 11]),
      hs("CP", "Yoga, Pilates, and Fitness Training", [10, 11]),
      ms("CP", "Physical Education 6", [6]),
      ms("CP", "Physical Education 7", [7]),
      ms("CP", "Physical Education 8", [8]),
    ],
    ROP: [
      hs("CP", "Introduction to Health Careers", [10, 11]),
      hs("CP", "Sports Medicine-Athletic Trainer 1", [10, 11]),
      hs("CP", "Sports Medicine II", [11, 12]),
      hs("CP", "Nursing Careers", [11, 12]),
      hs("CP", "Medical Occupations", [11, 12]),
      hs("CP", "Emergency Medical Responder", [10, 11]),
      hs("CP", "Introduction to Criminal Justice", [10, 11]),
      hs("Honors", "Criminal Justice Academy", [11, 12]),
      hs("CP", "Economics of Business Ownership", [11, 12]),
      hs("CP", "Integrated Marketing Communications", [10, 11]),
      hs("CP", "Sports/Entertainment Marketing", [10, 11]),
      hs("CP", "Developmental Psychology of Children I", [11, 12]),
      hs("CP", "Developmental Psychology of Children II", [11, 12]),
      hs("CP", "Cybersecurity/ICT Essentials", [11, 12]),
      hs("CP", "Internet Engineering I (CCNA-1)", [11, 12]),
      hs("CP", "Internet Engineering II (CCNA2)", [12]),
      hs("CP", "Automotive Technology", [11, 12]),
      hs("CP", "Auto Body Repair I", [12]),
      hs("CP", "Auto Body Repair II", [12]),
      hs("CP", "PLTW Computer Integrated Manufacturing", [11, 12]),
      hs("Honors", "Hon. Civil Engin & Archit.", [12]),
      hs("Honors", "Hon. Aerospace Engineering", [12]),
      hs("CP", "Video Game Art and Design", [11, 12]),
      hs("CP", "Animation and Motion Graphics 1", [11, 12]),
      hs("Honors", "Honors Artist Portfolio", [11, 12]),
      hs("CP", "Construction Technology 1", [10, 11, 12]),
      hs("CP", "Construction Technology 2", [11, 12]),
    ],
  };

  const countAP = Object.values(window.COURSE_CATALOG)
    .flat()
    .filter((c) => c.level === "AP").length;
  if (typeof console !== "undefined" && console.debug) {
    console.debug("CourseSync: AP course count in catalog =", countAP);
  }
})();
